@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg1MjA4NzEzfQ.O5gxNk0eJZqwH4DltOa56MEs7tvY4CN61uyKCQGW86g

### Get all tasks
GET {{baseUrl}}/api/v1/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

### Create task
POST {{baseUrl}}/api/v1/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Học FastAPI",
    "description": "Làm bài tập quản lý Task với SQLAlchemy và JWT"
}

### Get task by id
GET {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Update task
PUT {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Học FastAPI ver2 (Đã cập nhật)",
    "description": "Cập nhật mô tả mới cho task",
    "status": "in_progress"
}

### Update task status (PATCH)
PATCH {{baseUrl}}/api/v1/tasks/1/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "done"
}

### Delete task
DELETE {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}