@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg1MjEwNjgwfQ.0AFCVpTLJ24QVkEIxmqG4ZNuySKpgPfphNd15eylWwU

### 1. Get all tasks (Mặc định: page=1, page_size=10, sort_by=created_at, order=desc)
GET {{baseUrl}}/api/v1/tasks?page=1&page_size=5
Content-Type: application/json
Authorization: Bearer {{token}}

### 2. Get tasks lọc theo trạng thái (status: todo, in_progress, done)
GET {{baseUrl}}/api/v1/tasks?status=todo&page=1&page_size=5
Content-Type: application/json
Authorization: Bearer {{token}}

### 3. Get tasks tìm kiếm theo từ khóa và sắp xếp tăng dần
GET {{baseUrl}}/api/v1/tasks?keyword=FastAPI&sort_by=title&order=asc
Content-Type: application/json
Authorization: Bearer {{token}}

### 4. Create task
POST {{baseUrl}}/api/v1/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Học FastAPI",
    "description": "Làm bài tập quản lý Task với SQLAlchemy và JWT"
}

### 5. Get task by id
GET {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

### 6. Update task
PUT {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Học FastAPI ver2 (Đã cập nhật)",
    "description": "Cập nhật mô tả mới cho task",
    "status": "in_progress"
}

### 7. Update task status (PATCH)
PATCH {{baseUrl}}/api/v1/tasks/1/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "done"
}

### 8. Delete task
DELETE {{baseUrl}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}