@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg1MTI4NTAzfQ.oyu285s48jbAuvuy3zS_l4qcXRNTvN30_3SxfOWPkTY

### 1. Get me
GET {{baseUrl}}/api/v1/users/me
Content-Type: application/json
Authorization: Bearer {{token}}